version: 2

jobs:
  test:
    docker:
      - image: gcr.io/cloud-marketplace-containers/google/bazel:3.5.0
    steps:
      - checkout
      - run:
          command: |
            bazel test

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
