---
name: badges-update
on:
  schedule:
    - cron:  '* */3 * * *'
  workflow_dispatch:

jobs:
  badge-update:
    runs-on: ubuntu-latest
    container: quay.io/kubevirtci/bootstrap:v20210715-d0c2b78
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.KUBEVIRT_BOT_TOKEN }}
    - name: badge update for kubevirt/kubevirt
      env:
        GITHUB_TOKEN: ${{ secrets.KUBEVIRT_BOT_TOKEN }}
        SOURCE: kubevirt/kubevirt
      run: |
        echo -n $GITHUB_TOKEN > $(pwd)/token

        bazelisk run //cmd/stats -- \
          --gh-token $(pwd)/token \
          --log-level debug \
          --source ${SOURCE} \
          --path $(pwd)/output

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: KubeVirt Bot
        author_email: kubevirtbot@redhat.com
        message: 'Badges updated'
        add: 'output/*'
