name: badge-update
on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  badge-update:
    runs-on: ubuntu-latest
    container: kubevirtci/bootstrap:v20210112-b29dfd7
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.BOT_TOKEN }}
    - name: badge update for kubevirt/kubevirt
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        SOURCE: kubevirt/kubevirt
      run: |
        echo -n $GITHUB_TOKEN > $(pwd)/token

        bazelisk run //cmd/stats -- \
          --gh-token $(pwd)/token \
          --log-level debug
          --source ${SOURCE}
          --path $(pwd)/badges/${SOURCE}

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Federico Gimenez
        author_email: fgimenez@redhat.com
        message: 'Badges updated'
        add: 'badges/*'
