name: ci-health-tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: kubevirtci/bootstrap:v20210112-b29dfd7
    steps:
    - run: |
        echo -n $GITHUB_TOKEN > $(pwd)/token

        bazelisk test ... --action_env GITHUB_TOKEN_PATH=$(pwd)/token
